(source gnu)
(source melpa)

;; Comment out this chunk when updating misenplace
;; (depends-on "undo-tree" :git "http://www.dr-qubit.org/git/undo-tree.git") ;; Has issues with cask
;; (depends-on "xelb" :git "https://github.com/ch11ng/xelb.git") ;; Has issues with cask
(depends-on "exwm" :git "https://github.com/ch11ng/exwm.git") ;; Has issues with cask
;; (depends-on "exwm-x" :git "https://github.com/tumashu/exwm-x.git") ;; Has issues with cask
;; (depends-on "alert" :git "https://github.com/jwiegley/alert.git") ;; Has issues with Cask
;; Comment out this chunk when updating misenplace

(depends-on "auctex")
(depends-on "auctex-latexmk")
 (depends-on "auto-complete")
 (depends-on "all-the-icons")
 (depends-on "all-the-icons-ivy-rich")
 (depends-on "ivy-rich")
 (depends-on "ace-jump-mode")
 (depends-on "bind-key")
 (depends-on "cask")
 (depends-on "cask-mode")
 (depends-on "company")
 (depends-on "lsp-ui")
 (depends-on "lsp-ivy")
 (depends-on "lsp-treemacs")
 (depends-on "company-lsp")
 (depends-on "dap-mode")
 (depends-on "command-log-mode")
 (depends-on "counsel")
 (depends-on "counsel-org-clock")
 (depends-on "dash")
 (depends-on "dashboard")
 (depends-on "dimmer")
 (depends-on "dockerfile-mode")
 (depends-on "doom-modeline")
 (depends-on "dumb-jump")
 (depends-on "drag-stuff")
 (depends-on "ecukes")
 (depends-on "eglot")
 (depends-on "ein")
 (depends-on "elpy")
 (depends-on "elscreen")
 (depends-on "ert-async")
 (depends-on "ert-runner")
 (depends-on "evil")
 (depends-on "evil-nerd-commenter")
;;  (depends-on "eyebrowse")
 (depends-on "ess")
 (depends-on "esup")
 (depends-on "exec-path-from-shell")
 (depends-on "expand-region")
 (depends-on "f")
 (depends-on "flycheck")
 ;; (depends-on "frame-cmds")
 (depends-on "flycheck-cask")
 (depends-on "forge")
 (depends-on "fringe-helper")
 (depends-on "git-gutter")
 (depends-on "git-gutter-fringe")
 (depends-on "goto-chg")
 (depends-on "htmlize")
 (depends-on "idle-highlight-mode")
 (depends-on "ivy")
 ;; (depends-on "ivy-bibtex")
 (depends-on "ivy-posframe")
 (depends-on "ivy-prescient")
 (depends-on "lorem-ipsum")
 (depends-on "magit")
 (depends-on "misenplace-snippets" :git "https://gitlab.com/jordans1882/misenplace-snippets.git" :files ("*.el" "snippets"))
 (depends-on "mpc")
 (depends-on "multiple-cursors")
 (depends-on "nyan-mode")
 (depends-on "ob-mermaid")
 (depends-on "org")
 (depends-on "org-bullets")
 (depends-on "org-projectile")
 (depends-on "org-ref")
 (depends-on "ox-reveal")
 (depends-on "org-pomodoro")
 (depends-on "pallet")
 (depends-on "pdf-tools")
 (depends-on "polymode")
 (depends-on "poly-markdown")
 (depends-on "poly-org")
 (depends-on "poly-R")
 (depends-on "popwin")
 (depends-on "prodigy")
 (depends-on "powerline")
 (depends-on "prescient")
 (depends-on "projectile")
 (depends-on "rainbow-delimiters")
 (depends-on "ranger")
 (depends-on "rg")
 (depends-on "s")
 (depends-on "slack")
 (depends-on "smartparens")
 (depends-on "smex")
 (depends-on "sublimity")
 (depends-on "swiper")
 (depends-on "treemacs")
 (depends-on "treemacs-evil")
 (depends-on "treemacs-projectile")
 (depends-on "treemacs-icons-dired")
 (depends-on "treemacs-magit")
 (depends-on "undercover")
 (depends-on "use-package")
 (depends-on "vterm")
 (depends-on "web-mode")
 (depends-on "yasnippet")
 (depends-on "yasnippet-snippets")
 (depends-on "counsel-projectile")
 (depends-on "which-key")

(depends-on "misenplace" :git "https://gitlab.com/jordans1882/misenplace.git" :branch "master" :files ("*.el" "assets"))

